const {test,expect}=require('@playwright/test');
test('ニュースの写真を先に取得し、編集した本文と一緒に共有する',async({page})=>{
 await page.addInitScript(()=>{
  localStorage.setItem('sanrioCloudSyncKey','test-key');
  Object.defineProperty(navigator,'canShare',{value:()=>true,configurable:true});
  Object.defineProperty(navigator,'share',{value:async data=>{window.sharedNews={text:data.text,files:data.files.map(f=>({name:f.name,type:f.type}))}},configurable:true});
 });
 await page.route('**/news.php?**',async route=>{
  const u=new URL(route.request().url()),action=u.searchParams.get('action');
  if(action==='image')return route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  const item={title:'ハローキティ＆クロミの新作',source:'PR TIMES',date:'2026-10-01',image:'https://example.invalid/thumb.png',facts:[{kind:'schedule',text:'10月上旬発売予定です。'},{kind:'price',text:'価格は1,290円（税込）です。'}],url:'https://prtimes.jp/main/html/rd/p/000000122.000013308.html',images:Array.from({length:5},(_,i)=>'https://example.invalid/image'+i+'.png'),paragraphs:['10月上旬の新作アイテムについての発表です。']};
  return route.fulfill({json:action==='list'?{ok:true,items:[item]}:{ok:true,item}});
 });
 await page.goto('/');
 await page.getByRole('tab',{name:'新作ニュース',exact:true}).click();
 await expect(page.locator('#todayHomePanel')).not.toBeVisible();
 await expect(page.locator('#lovelyPanel')).not.toBeVisible();
 await page.locator('#newsCharacter').selectOption('cinnamoroll');
 await expect(page.locator('#newsList article')).toHaveCount(0);
 await page.locator('#newsCharacter').selectOption('kuromi');
 await expect(page.locator('#newsList article')).toHaveCount(1);
 await page.locator('#newsSourceFilter').selectOption('official');
 await expect(page.locator('#newsList article')).toHaveCount(0);
 await page.locator('#newsSourceFilter').selectOption('pr');
 await page.locator('#newsType').selectOption('event');
 await expect(page.locator('#newsList article')).toHaveCount(0);
 await page.locator('#newsFilterReset').click();
 await page.locator('#newsType').selectOption('goods');
 await expect(page.locator('#newsList article')).toHaveCount(1);
 await page.locator('#newsFilterReset').click();
 await page.locator('#newsList').getByRole('button',{name:'投稿準備',exact:true}).click();
 await expect(page.locator('#newsShare')).toBeEnabled();
 await expect(page.locator('#newsBrowse')).not.toBeVisible();
 await expect(page.locator('#newsImages img')).toHaveCount(5);
 expect(await page.locator('#newsEditor').evaluate(el=>el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(-1);
 expect(await page.locator('#newsEditor').evaluate(el=>el.getBoundingClientRect().top)).toBeLessThan(100);
 await expect(page.locator('#newsText')).toHaveValue(/10月上旬発売予定/);
 await expect(page.locator('#newsText')).toHaveValue(/1,290円/);
 await expect(page.locator('#newsText')).toHaveValue(/🎀/);
 await page.getByRole('button',{name:'写真2を前へ',exact:true}).click();
 await page.locator('.news-photo').filter({has:page.getByAltText('記事の写真 1', {exact:true})}).getByRole('checkbox').uncheck();
 await page.locator('.news-photo').filter({has:page.getByAltText('記事の写真 5', {exact:true})}).getByRole('checkbox').check();
 await page.locator('#newsText').fill('確認済みの紹介文\n詳細：https://prtimes.jp/main/html/rd/p/000000122.000013308.html');
 await page.locator('#newsBack').click();
 await expect(page.locator('#newsBrowse')).toBeVisible();
 await expect(page.locator('#newsEditor')).not.toBeVisible();
 await page.locator('#newsList').getByRole('button',{name:'投稿準備',exact:true}).click();
 await expect(page.locator('#newsText')).toHaveValue(/確認済みの紹介文/);
 await expect(page.locator('#newsImages .news-photo').first()).toContainText('1枚目');
 await expect(page.locator('#newsImages .news-photo').first().locator('img')).toHaveAttribute('alt','記事の写真 2');
 await page.locator('#newsShare').click();
 const shared=await page.evaluate(()=>window.sharedNews);
 expect(shared.text).toContain('確認済みの紹介文');
 expect(shared.files.map(f=>f.name)).toEqual(['news-2.png','news-3.png','news-4.png','news-5.png']);
 await page.locator('#newsDone').click();
 await expect(page.locator('#newsList article')).toHaveCount(0);
 await page.locator('#newsFilter').selectOption('hidden');
 await expect(page.locator('#newsList')).toContainText('投稿済み');
 await page.reload();
 await page.getByRole('tab',{name:'新作ニュース',exact:true}).click();
 await expect(page.locator('#newsList article')).toHaveCount(0);
 await page.locator('#newsFilter').selectOption('hidden');
 await page.locator('#newsList').getByRole('button',{name:'戻す',exact:true}).click();
 await page.locator('#newsFilter').selectOption('new');
 await expect(page.locator('#newsList article')).toHaveCount(1);
 await expect(page.locator('#newsList')).toContainText('発表 10/1');
 await expect(page.locator('#newsList img')).toHaveAttribute('src','https://example.invalid/thumb.png');
 await page.getByRole('tab',{name:'今日の候補',exact:true}).click();
 await expect(page.locator('#newsPanel')).not.toBeVisible();
});
