<?php
try{
 define('SPH_NEWS_TEST',true);require __DIR__.'/../server/lolipop/news.php';
 $feeds=array_values(array_filter(news_feeds(),static fn($f)=>in_array($f['kind'],['arts','rement'],true)));$bodies=news_fetch_feeds($feeds);$counts=[];$errors=[];
 foreach($feeds as $i=>$feed){if($bodies[$i]===null)throw new RuntimeException();$rows=$feed['kind']==='arts'?news_arts_rows($bodies[$i],time()):news_extra_enrich(news_rement_rows($bodies[$i]),$errors);if(!$rows)throw new RuntimeException();$counts[$feed['kind']]=count($rows);}
 $urls=['https://www.takaratomy-arts.co.jp/items/item.html?n=Y111372','https://www.re-ment.co.jp/product/r70125'];
 foreach($urls as $url){$item=news_detail($url);if(empty($item['tipsOnly'])||empty($item['images'])||empty($item['schedule'])||!empty($item['date']))throw new RuntimeException();$bytes=news_fetch($item['images'][0],6000000);if(!getimagesizefromstring($bytes))throw new RuntimeException();}
 echo 'Live manufacturer news: arts '.$counts['arts'].', rement '.$counts['rement']."; identities, official release precision and real photos verified.\n";
 if(isset($argv[1])){$config=require $argv[1];foreach(array_merge(['list'],$urls) as $target){$url='https://fan-info.zombie.jp/sanrio-fan/sanrio-sync/news.php?'.http_build_query(['action'=>$target==='list'?'list':'detail','url'=>$target==='list'?'':$target]);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_TIMEOUT=>40,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$config['sync_key']]]);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$data=json_decode((string)$body,true);if($status!==200||empty($data['ok']))throw new RuntimeException();if($target==='list'){foreach(['タカラトミーアーツ','リーメント'] as $source)if(!array_filter($data['items']??[],static fn($i)=>($i['source']??'')===$source))throw new RuntimeException();}elseif(empty($data['item']['tipsOnly'])||empty($data['item']['images']))throw new RuntimeException();}echo "Deployed manufacturer news: both sources and requested details verified.\n";}
}catch(Throwable $e){fwrite(STDERR,"Manufacturer verification failed; private details withheld.\n");exit(1);}
